### ISSUE TITLE
About the mask

### ISSUE THREAD

**Issue by YihaoWEI** [ex4sperans/pruning_with_tensorflow#1]
Hi, thanks to your great work!   
I have found that your weight will fall into a frozen state when they are smaller than the threshold in your mask. Will it affect the accuracy? 
` def _apply_prune_on_grads(self,
                              grads_and_vars: list,
                              threshold: float):

        # we need to make gradients correspondent
        # to the pruned weights to be zero

        grads_and_vars_sparse = []

        for grad, var in grads_and_vars:
            if 'weights' in var.name:
                small_weights = tf.greater(threshold, tf.abs(var))
                mask = tf.cast(tf.logical_not(small_weights), tf.float32)
                grad = grad * mask

            grads_and_vars_sparse.append((grad, var))
               
        return grads_and_vars_sparse`

I think the `tf.greater` will cause the problem. I think it should be a comparison of zero value or not.

**Comment by YihaoWEI** [comment]
![weights_distribution_after_pruning_36000](https://user-images.githubusercontent.com/30313622/45467869-6128cd80-b754-11e8-990b-48f688293531.png)

**Comment by ex4sperans** [comment]
Hi! 

The main idea is to make these small weights to be exactly zero, and don't let them change their values during finetuning stage. Accuracy is indeed affected to some extent, but the drop is typically negligible (1-2% or so).

**Comment by YihaoWEI** [comment]
Hi ex4sperans, thx for your reply. I learned a lot from your project. Many thanks again!
